SystemConsultantGroup/S-top-frontend

src/components/common/SearchInput/SearchInput.story.tsx
src/components/common/SearchInput/SearchInput.test.tsx
src/components/common/SearchInput/SearchInput.tsx
src/components/common/SearchInput/index.ts

Issue: #5 
- 검색 입력 컴포넌트 코드를 작성했습니다.
- 컴포넌트 배경 색깔을 지정하지 못했습니다. 함께 코딩하면서 맞춰나가면 좋을 것 같습니다.

[FEAT] 검색 입력

---

src/components/common/Header/Header.module.css
src/components/common/Header/Header.story.tsx

Issue: #47 
- fade in/out 스타일을 구현하는 데에 display 대신 visibility를 사용
- transition visibility n opacity
- https://stackoverflow.com/questions/3331353/transitions-on-the-css-display-property

[FIX] ease-in-out transition n storybook layout fullscreen

---

src/components/common/Tabs/ProjectSelectTab/ProjectSelectTab.module.css
src/components/common/Tabs/ProjectSelectTab/ProjectSelectTab.story.tsx
src/components/common/Tabs/ProjectSelectTab/ProjectSelectTab.test.tsx
src/components/common/Tabs/ProjectSelectTab/ProjectSelectTab.tsx
src/components/common/Tabs/index.ts
src/theme/AppTheme.ts

이슈: #8 
- 프로젝트 선택 탭을 추가하였습니다.
- 스토리 canvas 너비 제한 때문에 탭 부분이 줄바꿈이 되어 보이는데, 실제로 페이지에 적용하면 정상적으로 표시되긴 합니다.

[FEAT] 프로젝트 선택 탭 추가

---

src/components/common/CardBadge/CardBadge.module.css
src/components/common/CardBadge/CardBadge.story.tsx
src/components/common/CardBadge/CardBadge.test.tsx
src/components/common/CardBadge/CardBadge.tsx
src/components/common/CardBadge/index.ts

작성자: @hynseok 
- 프로젝트 등 카드에 보여지는 뱃지를 추가하였습니다.

[FEAT] 카드 뱃지 컴포넌트 추가

---

package-lock.json
package.json
src/app/layout.tsx
src/app/login/kakao/page.tsx
src/components/common/Auth/AuthProvider.tsx
src/components/common/Auth/getServerSideToken.ts
src/components/common/Auth/index.ts
src/components/common/DataTable/DataTableUsage.tsx
src/components/pages/KakaoAuth/KakaoAuth.tsx
src/components/pages/KakaoAuth/index.ts
src/constants/Auth.ts
src/types/jwtPayload.ts
src/types/user.ts
src/utils/CommonAxios/CommonAxios.ts
src/utils/CommonAxios/index.ts
src/utils/fetcher/fetcher.ts
src/utils/fetcher/index.ts

작성자: @hynseok 
- 백엔드 통신에서 인증시 필요한 accessToken을 관리하는 Auth Context와 Provider를 작성하였습니다.
- baseURL및 accessToken을 요청 기본값으로 설정하여 사용하는 CommonAxios를 작성하였습니다.
- 서버컴포넌트에서 브라우저의 액세스토큰 및 리프레시 토큰을 얻어올 수 있는 getServerSideToken을 작성하였습니다.
- swr 및 서버사이드 데이터페칭에 이용할 수 있는 fetcher 함수를 작성하였습니다.
- 카카오 로그인을 위한 페이지를 작성하였습니다. 로그인페이지에서 카카오 로그인 버튼을 누르면 
https://kauth.kakao.com/oauth/authorize?response_type=code&client_id=<카카오 클라이언트 id>&redirect_uri=<사용하게될 도메인>/auth/login/kakao 
으로 이동하도록 로그인 페이지를 구현하면 됩니다. (cc. @moony1204)
close #56

[FEAT] 로그인, 로그아웃 모듈 추가

---

package-lock.json
src/components/common/GalleryPreview/GalleryPreview.module.css
src/components/common/GalleryPreview/GalleryPreview.tsx

이슈: #76 
- 갤러리 미리보기 컴포넌트에서 useMantineTheme을 사용한 부분을 수정하였습니다.
- 원래 의도는 라이트모드/다크모드 사용에 따라서 텍스트 색상에 맞추기 위해 해당 훅을 사용했던 것이었는데, 일단 해당 부분을 삭제하고, 따로 스타일 설정은 하지 않았습니다.
- 크게 거슬리는 요소는 아니라고 생각해서, 페이지에 적용했을 때 아이콘 색상이 이상해보이면 그때 수정해도 괜찮을 것 같습니다.
- mantine card 컴포넌트에 inline-block 스타일 속성을 추가하여 자식 요소의 크기에 맞추도록 수정하였습니다.

[FIX] 갤러리 미리보기 컴포넌트 버그 수정

---

package-lock.json
src/components/common/Buttons/PrimaryButton/PrimaryButton.test.tsx
src/components/common/TextInput/TextInput.tsx
src/components/common/VRLink/VRLink.module.css

- TextInput Wrapper 스타일 지정 가능하도록 수정
- VRLink max-height 스타일 삭제
https://github.com/SystemConsultantGroup/s-top-frontend/blob/5c50f44b323db48a560ef3537ec6b32c3cfb0c7a/src/components/common/TextInput/TextInput.tsx#L4-L9
wrapperClasses에 위와 같이 dict를 만들고 해당 스타일을 넘기면 됩니다. 아래는 예시입니다:
```
import styles from "./styles.module.css";
<TextInput wrapperClasses={{
root: styles.root,
description: styles.description
}} />
```

[FIX] TextInput과 VRLink 각각 스타일 수정

---

src/app/(admin)/admin/(contents)/quiz-list/page.tsx
src/components/pages/AdminQuizListSection/AdminQuizListSection.tsx
src/constants/DataTableHeaders.ts
src/hooks/swr/useQuizResults.tsx
src/types/quiz.ts

작성자: @hynseok
- 관리자 퀴즈 결과 목록을 조회하는 페이지를 추가하였습니다.
related issue #45

[FEAT] 관리자 퀴즈 결과 목록 페이지 추가

---

src/app/(admin)/admin/projects/proposals/[id]/page.tsx
src/app/(admin)/admin/projects/proposals/page.tsx
src/components/pages/AdminInquiriesListSection/AdminInquiriesListSection.tsx
src/components/pages/AdminNoticeEditForm/AdminNoticeEditForm.module.css
src/components/pages/AdminNoticeEditForm/AdminNoticeEditForm.tsx
src/components/pages/AdminNoticeListSection/AdminNoticeListSection.tsx
src/components/pages/AdminProjectsEditSection/ProjectCreateSection.tsx
src/components/pages/AdminProjectsEditSection/ProjectsExcelCreateSection.tsx
src/components/pages/AdminProjectsListSection/AdminProjectsListsSection.tsx
src/components/pages/AdminProposalsListSection/AdminProposalsListSection.tsx
src/components/pages/GalleryListSection/GalleryListSection.tsx
src/components/pages/InterviewListSection/InterviewListSection.tsx
src/components/pages/JobInterviewListSection/JobInterviewListSection.tsx
src/constants/DataTableHeaders.ts
src/hooks/swr/useProposals.tsx
src/hooks/useFiles/useFiles.ts
src/types/proposals.ts
src/utils/handleDownloadFile/handleDownloadFile.ts
src/utils/handleDownloadFile/index.ts

작성자: @hynseok
- 어드민 페이지에서 파일 업로드 관련 오류가 발생하여 수정했습니다.
- 모든 목록 조회 페이지 검색 입력시 페이지 넘버를 1 설정하도록 수정했습니다.
- 프로젝트 일괄등록 기능을 추가했습니다.

[FIX] 어드민페이지 오류 수정 / 프로젝트 일괄등록 추가

---

src/components/common/ProjectCard/ProjectCard.tsx
src/components/pages/EventAwardView/EventAwardView.tsx
src/constants/LookupTables.ts
src/constants/UserNavigations.ts

이슈: #41 
- 작품 수상 결과 페이지 API 연결을 하였습니다.
- 내비게이션 바에서 Events의 하위 항목으로 "작품 수상 결과"를 추가하였습니다.
- `AWARD_TYPE_LOOKUP_TABLE`에서 프로젝트 수상 status에 따라 상의 명칭을 임의로 설정해놓았는데, 정확한 명칭으로 변경해야 합니다.

작품 수상 결과 페이지 API 연결

---

src/components/common/VideoCard/VideoCard.module.css

Issue: #133 
- 제목이 길어지면 text가 한 줄 내려오면서 videocard가 서로 다른 height를 가지게 되는데 넘어가는 부분을 `...`로 수정했습니다.

[FIX] VideoCard 제목 text-overflow 처리

---

src/components/pages/EventPeriodForm/EventPeriodForm.tsx

작성자: @shj1081 
- `EventPeriodForm.tsx`의 `handleChangePeriod` 함수에서 날짜 포맷을 BE의 요구사항과 동일하게 수정하였습니다.
- 이벤트가 아무것도 없는 경우 제대로 설정이 되는 것을 확인하였습니다.
- 그런데 이벤트의 기간 변경의 경우, `EventPeriodForm.tsx` 의 코드를 보았을 때, 기존의 이벤트 기간을 업데이트 하는 BE 의 API를 사용하지 않아 두번째 이벤트를 설정하려 할때 기존의 이벤트 기간과 겹칠경우, BE의  `해당 연도의 행사 기간이 이미 존재합니다` 가 뜹니다
- BE의 eventPeriod 관련해서 `updateEventPeriod` 를 사용해야 해당 이벤트 기간을 변경 가능합니다.
> 용도가 이벤트 기간 수정이 아닌 단순 1회성 추가이기에 추가 코드 수정은 하지 않도록 하겠습니다.

[FIX] 관리자 페이지 이벤트 기간 설정 안되는 문제 해결

---

src/components/common/Header/elements/HeaderToolBar.tsx
src/components/common/RegisterForm/registerForm.tsx
src/components/pages/KakaoAuth/KakaoAuth.tsx
src/types/jwtPayload.ts

작성자: @shj1081 
- jwt 의 유저 타입을 담고있는 필드명인 `userType` 과 jwt 페이로드 필드명인  `type` 간의 이름 불일치로 나타난 문제임을 확인
- 페이로드 필드명 `userType` 으로 수정
- 회원 가입 완료 후 랜딩 페이지로 못돌아가는 문제는 router가 랜딩페이지로 push해주는 구문이 없어서 발생 -> 추가
- 로그아웃의 경우, onClick action이 AuthProvider의 logout 함수가 아닌 BE 로그아웃 api 로의 직접 요청만으로 설정되있어 나는 문제임을 확인
- 해당 onClick action 수정
- 이건 진짜 찾는데, 오래 걸렸습니다...
- 로그가 브라우저에 찍히는 줄 몰라서 한참 해멨습니다.
- 이제 드디어 쿠키 한번 지우시면 시크릿 모드아니여도 로그인 로그아웃 멀쩡하게 가능합니다!!!

[FIX] 새 유저 회원 가입 창이 아닌 랜딩로 가는 문제/회원가입 완료 후 랜딩으로 못가는 문제 + 로그 아웃 미기능 문제 해결

---

src/components/pages/ProjectDetail/ProjectDetailInfo.tsx
src/components/pages/ProjectDetail/ProjectDetailInquiry.tsx

- 2군데 스펠링 미스가 남아있길래 마저 수정합니다.
- 프로젝트 상세조회 페이지에서 로그인 없이 프로젝트 문의, 좋아요, 북마크 클릭할 경우 경고를 띄우고 행위를 하지 못하도록 수정 (auth의 로그인 확인 기능을 이용)
- 근데 프로젝트 문의 버튼이 프로젝트 상세조회에 위에 하나 아래하나 있어서 이게 두개나 있는 건가요?

[FIX] 프로젝트 상세조회 페이지에서 inquiry 버튼 redirect url 수정, 비로그인 시 경고 메세지 절차 수행

---

src/app/(user)/infodesk/inquiries/projectQA.module.css
src/components/common/Noticeboard/Noticeboard.module.css
src/styles/UserBoard.module.css

작성자: @jaychang99 
다음의 페이지들에서 모바일 UI 를 개선합니다. 
* `/infodesk/notices`
* `/infodesk/notices/[id]`
* `/event/notices`
* `/event/notices/[id]`
* `/infodesk/inquiries`
* `/infodesk/inquiries/[id]`
| Before | After |
|--------|-------|
| <img src=https://github.com/user-attachments/assets/2b29b728-8dec-4ea3-a1e5-40ce3b3bd749 width=200 /> | <img src=https://github.com/user-attachments/assets/0acb4c82-7d86-4d3a-b88c-d47540eedec0 width=200 /> |
| 페이지네이션 없음, 필터 및 검색 안 보임 | 페이지네이션, 필터, 검색 이용가능 | 
| Before | After |
|--------|-------|
| <img src=https://github.com/user-attachments/assets/cb7f13d0-37e7-48bc-80cd-ce36050b91e4 width=200 /> | <img src=https://github.com/user-attachments/assets/5fb4aeca-d8cb-40e4-8def-354282bf7202 width=200 /> |
| 제목 줄 넘어감, 패딩이 너무 큼 | 제목 한 줄 차지, 패딩 줄임 | 
* …

공지사항을 비롯한 게시판형 UI 에서 모바일 사용성을 개선합니다. 

---

src/components/common/VideoCard/VideoCard.tsx

작성자: @jaychang99
아래와 같은 이슈가 있어서 수정합니다. 
* 모바일 환경에서 퀴즈 모달 실행한 상태에서 퀴즈 선지를 누르는 순간, 화면 스크롤이 막혀서 다음 문제로 못 넘어감 '
아래 이미지 참고 부탁드립니다. 
* 문제의 원인 
지금 카드 UI 에 onClick 으로 `handleCardClick()` 이 이벤트 핸들러로 걸려있는데요,
문제는 카드 UI 를 감싸는 최외곽 div 안에 `<DetailsModal />` 과 `<QuizModal />` 이 들어있습니다.
그래서 모달 안에서의 어떤 클릭도, 카드를 클릭하는 동작처럼 작동할 것입니다.
(이벤트 버블링 — React 는 자체적인 이벤트 핸들링 메커니즘이 있습니다. 이벤트 버블링은 Modal 과 같은 portal 을 이용하는 경우라도 React 내부 메커니즘으로 JSX 상의 상위 요소로 버블링됩니다.)
일단 임시방편으로 `<VideoCard />` 최외곽을 `<></>` (React.Fragment) 로 감싸고, 카드 UI, 그리고 2개의 모달이 같은 수준에서 sibling 관계로 있을 수 있도록 했어요.
더 이상 div 의 onClick 핸들러가, 모달 내부 클릭에 반응하지 않습니다.
`<DetailsModal />` 내부에서 발생한 클릭 또한 handleCardClick() 을 호출했을 것입니다.
그러나 이미 detailsModalOpened 상태가 true 여서 눈에 띄는 UI 변화는 발생하지 않았을 것 같습니다.
(아! 참고로 추가적으로 말씀드리자면 내부에서도 react state 의 베일아웃(bailout) 이라는 것을 통해서 …

대담 영상 퀴즈 모달에서 선지 선택 시 스크롤이 불가해지는 문제를 수정합니다. 

---

src/components/common/RegisterForm/registerForm.tsx

fix: 회원가입 시 유저타입이 벡엔드의 유저타입 이름과 일치하지 않는 무제

---

src/utils/fetcher/fetcher.ts

작성자: @jaychang99
* `getServerSideToken()` 내부에서 `next/headers` 의 cookies 함수를 씁니다. 
* 그런데 이것이 server-side 에서만 이용가능해서, 프로덕션 모드로 코드를 작동시키면, 문제를 일으킵니다. (서버에서 실행되어야 할 코드가 클라이언트에서 실행되는 경우가 있습니다)
* 근본적인 해결책은 아니지만, 우선 `getIsomorphicToken` 이라는 새로운 함수를 만들어, 서버와 클라이언트에서 일단 다르게 동작할 수 있도록 했습니다. 최소한의 수정을 가하려는 의도가 있었습니다. 

카카오 로그인 하고 처음으로 돌아온 직후 Loading 표시 지속되고 이름 표시 안 되는 문제 임시로 해결

---

src/components/common/Auth/AuthProvider.tsx

작성자: @jaychang99
`<AuthProvider />` 의 무한 리렌더링으로 인해 초기접속 시 `/users/me` API 가 어떤 때는 1,000 회 이상 호출되는 경우가 있었습니다. 
`<AuthProvider />` 의 무한 리렌더링 원인 공유 
https://systemconsult-vqd4955.slack.com/archives/C079TP0861Y/p1739079535624679?thread_ts=1739076747.208969&cid=C079TP0861Y
```
아 <KakaoAuth /> 에 login 이 useEffect() 의 의존성 배열에 들어가있네요!
이렇게 되면 login 함수가 새로 생성될 때마다, 이 내부 로직이 돌아서, 무한 루프에 빠질 위험성이 있어요
지금같은 경우, login 함수 안에서 <AuthProvider /> 내부의 state 를 변경하고 있기 때문에
<KakaoAuth /> 에서 login 함수 호출
=> <AuthProvider /> 내부 상태 변경
=> <AuthProvider /> 내부 상태가 변경되었으니 리렌더링
=> login 함수 새로 생성됨 (참조 변경됨)
=> <KakaoAuth /> 의 useEffect 의 의존성 배열에 login 함수 있고, Object.is() 로 이전 함수랑 비교했을 때 달라졌음
=> <KakaoAuth /> 의 useEffect 내의 코드 재실행
=> <KakaoAuth /> 에서 login 함수 호출
=> (무한 반복….)
이렇게 된 것으로 보입니다.
```
```
이렇게 <AuthProvider /> 내부 …
```

AuthProvider 의 로그인 함수 호출로 인한 무한 리렌더링 이슈 해결

---

src/utils/fetcher/fetcher.ts

이슈 슬랙: https://systemconsult-vqd4955.slack.com/archives/C079TP0861Y/p1739105802170599
- 로그인 안 한 상태에서 프로젝트 보이지 않는 문제 해결
- accessToken 이 없는 경우 undefined 가 아니라 null 로 보내야 백엔드 서버에서 적절히 핸들링함. 
- https://github.com/SystemConsultantGroup/S-top-backend/blob/develop/src/main/java/com/scg/stop/auth/config/AuthUserArgumentResolver.java#L104

fix: accessToken 이 없는 경우 undefined 대신 null 을 보내어 에러를 해결한다

---

src/components/common/ProjectCard/ProjectCardLikeSection.tsx

작성자: @hynseok 
- 프로젝트 페이지 2025 탭과 전체 탭을 왔다갔다할 시 값이 고정되어있는 버그 및   
좋아요 클릭 후 탭 이동시 반영 안되는 버그 등 수정

[FIX] 프로젝트 페이지 탭이동시 좋아요, 북마크 등 고정되어있는 버그 수정

---

src/components/common/CommentBox/CommentBox.tsx

작성자: @shj1081 
- 뒤에 붙어있는 넘버링을 제거하고 익명만 표시하도록 간소화하였습니다
- anonymous 스펠링은 눈감아주시길...

[FIX] 익명 댓글 넘버링 제거

---

src/app/(user)/infodesk/cooperation/page.tsx
src/components/common/Auth/AuthProvider.tsx
src/utils/CommonAxios/CommonAxios.ts
src/utils/auth/setAccessTokenCookie.ts

작성자: @jaychang99
개념도
- access token 이 만료되었을 때는 refresh token 으로 access token 을 재요청해서 사용하게 합니다. 
- 기본적인 아이디어는 access token 을 이용한 기존 요청들이 '권한 없음 (status code = 401)' 의 이유로 실패한 경우 기존에 갖고 있던 refresh token 을 이용해 신규 access token 을 발급받는 것입니다. 실패한 요청들은 `failedRequestsQueue` 에 들어갑니다. 
- 이 과정에서 동시에 다수의 요청이 401 에러를 받으며 실패할 수 있으므로 `isGettingReissuedAccessToken` 으로 일종의 락 (lock) 을 걸어서 access token 재발급 요청은 1회만 갈 수 있도록 합니다. 
- refresh token 으로 성공적으로 신규 access token 을 발급받은 후에는 이전에 401 실패 응답을 받았던 요청들을 다시 요청하여 성공 응답을 받아내는 구조
- 현재 tanstack/react-query 와 같은 비동기 상태 (서버 상태) 관리 라이브러리를 사용하고 있지 않아서, 중복되는 요청이 굉장히 많이 가고 있습니다. 이부분은 향후 최적화 여지가 있습니다. 
- 다만, 직접 cache mechanism, request deduplication 등과 같은 것을 구현하는 것은 바퀴의 재발명이라고 생각을 합니다. 가능하다면 swr 또는 react-query 등과 같은 라이브러리를 스터디하고 적용을 하게 할 수도 있을 것 같습니다. 
- access token 의 …

[ENHANCE] access token 이 만료되었을 때는 refresh token 으로 access token 을 재요청해서 사용한다. 
