SystemConsultantGroup/S-top-frontend

.eslintrc.json
.gitignore
.storybook/main.ts
.storybook/preview.tsx
jest.config.ts
jest.setup.cjs
package-lock.json
package.json
src/components/common/Buttons/PrimaryButton/PrimaryButton.module.css
src/components/common/Buttons/PrimaryButton/PrimaryButton.story.tsx
src/components/common/Buttons/PrimaryButton/PrimaryButton.test.tsx
src/components/common/Buttons/PrimaryButton/PrimaryButton.tsx
src/components/common/Buttons/index.ts
src/utils/test-utils/index.ts
src/utils/test-utils/render.tsx
tsconfig.json

- storybook 및 Jest/react testing library를 셋팅하였습니다.
.

[Feat] testing setup

---

.github/workflows/storybook.yml
package-lock.json
package.json

작성자: @hynseok 
- chromatic을 셋팅하여 pr시 배포된 스토리북을 확인할 수 있도록 하였습니다.

[FEAT] chromatic setup

---

src/components/common/Pagination/Pagination.tsx

작성자: @obinox 
issue: #10 
- 페이지네이션 추가
- 모양 적용 x

[FEAT] 페이지네이션 추가

---

src/components/common/Cards/Aihub/Aihub.module.css
src/components/common/Cards/Aihub/Aihub.stories.tsx
src/components/common/Cards/Aihub/Aihub.test.tsx
src/components/common/Cards/Aihub/Aihub.tsx

작성자: @obinox
issue: #10 
- AI hub 카드 추가
- 글씨체 적용 x

[FEAT] AI hub 카드 추가

---

src/components/common/Cards/ViewPostDetail/ViewPostDetail.module.css
src/components/common/Cards/ViewPostDetail/ViewPostDetail.stories.tsx
src/components/common/Cards/ViewPostDetail/ViewPostDetail.test.tsx
src/components/common/Cards/ViewPostDetail/ViewPostDetail.tsx

작성자: @obinox
issue: #10 
- 게시글 상세보기 추가
- 이미지, 글씨체 적용 x

[FEAT] 게시글 상세보기 추가

---

src/components/common/Statics/Statics.module.css
src/components/common/Statics/Statics.stories.tsx
src/components/common/Statics/Statics.test.tsx
src/components/common/Statics/Statics.tsx

작성자: @obinox 
issue: #10 
- 막대그래프형 컴포넌트 제작
- 카드 형식 아직 작업 덜되었습니다.

[FEAT] 통계 보기

---

src/components/common/NoticeDetail/NoticeDetail.module.css
src/components/common/NoticeDetail/NoticeDetail.story.tsx
src/components/common/NoticeDetail/NoticeDetail.test.tsx
src/components/common/NoticeDetail/NoticeDetail.tsx
src/components/common/NoticeDetail/elements/FileDropdownMenu.tsx
src/components/common/NoticeDetail/elements/NoticeDetailHead.tsx
src/components/common/NoticeDetail/elements/NoticeDetailSprint.tsx
src/components/common/NoticeDetail/elements/NoticeDetailStage.tsx
src/components/common/NoticeDetail/elements/NoticeDetailToolbar.tsx
src/components/common/NoticeDetail/index.ts
src/components/common/Noticeboard/Noticeboard.module.css
src/components/common/Noticeboard/Noticeboard.story.tsx
src/components/common/Noticeboard/Noticeboard.test.tsx
src/components/common/Noticeboard/Noticeboard.tsx
src/components/common/Noticeboard/elements/NoticeContainer.tsx
src/components/common/Noticeboard/elements/NoticeHeading.tsx
src/components/common/Noticeboard/elements/NoticeItem.tsx
src/components/common/Noticeboard/index.ts

작성자: @chunzhi23
Issue: #5
- 게시판 목록과 세부 컴포넌트 코드를 작성하였습니다.
- 반응형 디자인을 제외하고 PR 올렸습니다. 추후 논의가 필요해 보입니다.
- 글자와 배경색이 맞지 않아 색깔은 디자인 틀에 맞춰 기본값으로 두었습니다. 차차 맞추겠습니다.
- 디자인에 포함되어있던 공유와 프린트 버튼의 작동을 프론트로 구현하지 못했습니다. 이것도 함께 개발하면서 맞추겠습니다.

[FEAT] 게시판 (게시판 목록, 게시판 세부)

---

src/components/common/TextInput/TextInput.story.tsx
src/components/common/TextInput/TextInput.test.tsx
src/components/common/TextInput/TextInput.tsx
src/components/common/TextInput/index.ts

Issue: #5 
- 텍스트 입력 컴포넌트 코드를 작성했습니다.
- 컴포넌트 배경 색깔을 지정하지 못했습니다. 함께 코딩하면서 맞춰나가면 좋을 것 같습니다.

[FEAT] 텍스트 입력

---

src/components/common/Footer/Footer.module.css
src/components/common/Header/Header.module.css
src/components/common/NoticeDetail/NoticeDetail.module.css
src/components/common/Noticeboard/Noticeboard.module.css

작성자: @chunzhi23
Issue: #48 
- 각 컴포넌트 module.css root에 적용되어있는 색상 변수를 해제
- 해제한 색상 변수는 추후 참고를 위해 root에 영향을 주지 않으면서 다르게 처리해 표시
- 컴포넌트 개발에 사용했던 개인 색상 변수를 root에 적용한 채로 그대로 병합해 여러 컴포넌트 색상 적용에 혼선을 주는 오류를 발견했습니다.

[FIX] test colors theme of a component remain

---

src/components/common/Buttons/DangerButton/DangerButton.module.css
src/components/common/Buttons/DangerButton/DangerButton.story.tsx
src/components/common/Buttons/DangerButton/DangerButton.test.tsx
src/components/common/Buttons/DangerButton/DangerButton.tsx
src/components/common/Buttons/OutlinedButton/OutlinedButton.module.css
src/components/common/Buttons/OutlinedButton/OutlinedButton.story.tsx
src/components/common/Buttons/OutlinedButton/OutlinedButton.test.tsx
src/components/common/Buttons/OutlinedButton/OutlinedButton.tsx
src/components/common/Buttons/PrimaryButton/PrimaryButton.module.css
src/components/common/Buttons/SecondaryButton/SecondaryButton.module.css
src/components/common/Buttons/SecondaryButton/SecondaryButton.story.tsx
src/components/common/Buttons/SecondaryButton/SecondaryButton.test.tsx
src/components/common/Buttons/SecondaryButton/SecondaryButton.tsx
src/components/common/Buttons/index.ts

이슈: #8 
- secondary button, outlined button, danger button을 추가하였습니다.
- primary button의 스타일을 수정하였습니다.

[FEAT] 버튼 추가

---

src/components/common/Dropdown/Dropdown.story.tsx
src/components/common/Dropdown/Dropdown.test.tsx
src/components/common/Dropdown/Dropdown.tsx

- onOptionClick을 Prop으로 빼는 드롭다운 수정 진행
- 외부에서 onOptionClick으로 setSelectedOption을 해줘야 합니다(?) 종민 리퀘스트.
fix #53

[BUG] 드롭다운 수정

---

src/components/common/Banner/Banner.module.css
src/components/common/Banner/Banner.tsx
src/components/common/VRLink/VRLink.module.css
src/components/common/VRLink/VRLink.tsx

작성자: @hynseok 
- 배너 및 vrlink 컴포넌트에서 next의 image 컴포넌트를 잘못 사용하여 발생한 오류를 수정하였습니다.
close/resolve/fix #52

[FIX] 배너오류 수정

---

src/components/common/Footer/Footer.module.css
src/components/common/Header/Header.module.css
src/components/common/NoticeDetail/NoticeDetail.module.css
src/components/common/Noticeboard/Noticeboard.module.css

[FIX] 색상 오류 수정

---

src/components/common/SubHeadNavbar/NavList.ts
src/components/common/SubHeadNavbar/SubHeadNavbar.module.css
src/components/common/SubHeadNavbar/SubHeadNavbar.story.tsx
src/components/common/SubHeadNavbar/SubHeadNavbar.test.tsx
src/components/common/SubHeadNavbar/SubHeadNavbar.tsx

이슈: #64 
- 서브 네비게이션바 코드를 작성했습니다.

[FEAT] 서브 네비게이션바

---

package-lock.json
package.json
src/app/layout.tsx
src/components/common/SWRProvider/SWRProvider.tsx
src/components/common/SWRProvider/index.ts

작성자: @hynseok 
- swr을 추가하였습니다.
- swr provider 를 추가하여 루트 레이아웃에 적용하였습니다.
.

[FEAT] swr 추가

---

src/components/common/VideoCard/VideoCard.story.tsx
src/components/common/VideoCard/VideoCard.test.tsx
src/components/common/VideoCard/VideoCard.tsx

이슈: #76 
- 비디오카드에서 북마크 여부를 필수 프롭으로 변화시키고 핸들러를 완전히 부모 영역으로 전환시켰습니당
- .

[FIX] 비디오카드 수정

---

src/utils/fetcher/fetcher.ts
src/utils/fetcher/index.ts
src/utils/handleDownloadFile/handleDownloadFile.ts
src/utils/handleDownloadFile/index.ts

작성자: @hynseok 
- fetcher를 수정, ServerSideFetcher 추가
- 아래와 같이 서버 컴포넌트/페이지에서 사용 가능
```
"use server";
import { ServerSideFetcher } from "@/utils/fetcher";
export default async function Home() {
const data = await ServerSideFetcher({ url: "/applications", query: { page: 0, size: 10 } });
console.log(data);
return <main>Hello, world!</main>;
}
```
- 파일 다운로드 유틸함수 추가
- 파일의 id를 넘기면 파일을 다운로드하는 handleFileDownload
- '' 파일의 url을 넘겨주는 getFileUrlById

[FEAT] 공통 유틸함수 수정 및 추가

---

package-lock.json
package.json
src/app/(admin)/admin/(boards)/event/notices/[id]/page.tsx
src/app/(admin)/admin/(boards)/event/notices/create/page.tsx
src/app/(admin)/admin/(boards)/event/notices/page.tsx
src/app/layout.tsx
src/components/pages/AdminNoticeEditForm/AdminNoticeEditForm.tsx
src/components/pages/AdminNoticeEditForm/EventImageSection.tsx
src/components/pages/AdminNoticeListSection/AdminNoticeListSection.tsx
src/components/pages/AdminSidebar/AdminSidebarMenu.tsx
src/hooks/swr/useNotices.tsx
src/hooks/useFiles/useFiles.ts
src/utils/handleDownloadFile/handleDownloadFile.ts
src/utils/handleDownloadFile/index.ts

작성자: @hynseok
- 이벤트 공지사항 목록조회 / 수정 / 등록 페이지 추가
- useFiles uploadFiles 기존 파일 무시하고 새로 업로드하던 버그 수정

[FEAT] 이벤트 공지사항 목록조회 / 수정 / 등록 페이지 추가

---

src/components/common/ProjectCard/ProjectCard.module.css

작성자: @hynseok 
- 참가팀명, 지도교수 텍스트 말줄임표 기능 추가하였습니다.

[fix] 프로젝트카드 말줄임표 수정

---

src/hooks/useFiles/useFiles.ts

작성자: @hynseok 
- 백엔드의 수정된 파일 업로드 api 에 맞게 코드를 수정하였습니다.

[FIX] 파일 업로드 api 수정

---

src/app/(admin)/admin/projects/inquiries/[id]/page.tsx
src/app/(admin)/admin/projects/inquiries/page.tsx
src/components/common/TitleRow/TitleRow.module.css
src/components/common/TitleRow/TitleRow.tsx
src/components/pages/AdminInquiriesEditForm/AdminInquiriesEditForm.tsx
src/components/pages/AdminInquiriesListSection/AdminInquiriesListSection.tsx
src/constants/DataTableHeaders.ts
src/hooks/swr/useInquiries.tsx
src/types/inquiry.ts

작성자: @hynseok 
- 프로젝트 문의 목록 페이지 추가
- 프로젝트 문의 조회 및 답변 페이지 추가
- 답변 등록 여부 관련 api 수정되면 추가로 수정이 필요합니다.
related issue #45

[FEAT] 프로젝트 문의 페이지 추가

---

package.json
src/components/common/ProjectCard/ProjectCard.tsx
src/components/common/ProjectCard/ProjectCardLikeSection.tsx
src/components/common/TextInput/TextInput.tsx
src/components/pages/AdminProjectsEditSection/ProjectCreateSection.tsx
src/components/pages/AdminProjectsListSection/AdminProjectsListRow.tsx
src/constants/DataTableHeaders.ts
src/hooks/useFiles/useFiles.ts

작성자: @hynseok 
- 프로젝트카드 좋아요 및 북마크 버튼 클릭 핸들러 추가했습니다.
.

[fix] 프로젝트카드 클릭 핸들러 추가

---

src/components/common/Noticeboard/Noticeboard.tsx
src/theme/AppTheme.ts

작성자: @chunzhi23
- 게시물이 없을 때 공통 안내 표지로 변경
- dropdown 색상 설정 정정

[FIX] noticeboard component 수정

---

package.json
src/app/layout.tsx

작성자: @hynseok
- 구글 애널리틱스 적용
- 배포시 환경변수로 NEXT_PUBLIC_GA_ID 를 설정해야합니다.
- 넥스트의 서드파티 라이브러리를 사용해봤는데 혹시 적용이 안되면 나중에 수정하겠습니다.

[FEAT] GA 적용

---

src/app/(user)/infodesk/inquiries/page.tsx
src/app/(user)/interviews/page.tsx
src/components/common/ProjectCard/ProjectCard.tsx
src/components/pages/AdminProjectsEditSection/ProjectCreateSection.tsx
src/components/pages/AdminProjectsListSection/AdminProjectsListsSection.tsx

작성자: @hynseok
- 테스트 환경 구성중 빌드오류로 배포가 되지 않아 수정하였습니다.
- 인포데스크 프로젝트 문의 페이지 목업데이터 수정
- 대담영상 비디오카드 북마크 토글버튼 핸들러 빈 함수 등록
- 관리자 프로젝트관련 페이지 타입 이름 수정

[HOTFIX] 빌드 오류 수정

---

src/app/(admin)/layout.tsx
src/components/common/Auth/AuthModule.ts

작성자: @hynseok 
- 페이지 접근 인증 모듈 추가
- 관리자페이지 등에서 사용
.

[FEAT] 페이지 접근 인증 모듈 추가

---

src/app/(user)/projects/[id]/page.tsx
src/components/common/CheckBox/CheckBox.tsx
src/components/common/CommentBox/CommentBox.module.css
src/components/common/CommentBox/CommentBox.tsx
src/components/pages/ProjectDetail/ProjectDetailComment.tsx
src/components/pages/ProjectDetail/ProjectDetailInfo.module.css
src/components/pages/ProjectDetail/ProjectDetailInfo.tsx
src/components/pages/ProjectDetail/ProjectDetailInquiry.tsx
src/components/pages/ProjectDetail/_type/comment.ts
src/components/pages/ProjectDetail/_type/project.ts

이슈번호: #41 
- 프로젝트 상세조회 페이지 API 연결
<공통 컴포넌트 수정사항>
- 체크박스 컴포넌트(Checkbox)
- 체크 상태를 업데이트하는 콜백 함수 추가
- 댓글 컴포넌트(CommentBox)
- 익명 선택 체크박스 추가
- 댓글 작성자에 익명이 아닌 경우 이름이 보여지도록 수정
- 댓글 작성 후 commentList state가 프로젝트 상세조회 후 업데이트되도록 수정

[FEAT] 프로젝트 상세조회 페이지 API 연결

---

src/app/(user)/event/notices/page.tsx
src/app/(user)/infodesk/notices/[id]/page.tsx
src/app/(user)/infodesk/notices/page.tsx
src/components/common/ProjectCard/ProjectCard.tsx
src/components/common/ProjectCard/ProjectCardLikeSection.tsx
src/constants/UserNavigations.ts
src/types/notice.ts

1. 공지사항 백엔드 포멧 동일하게 수정
- https://github.com/SystemConsultantGroup/S-top-backend/issues/117
2. 프로젝트 카드 예외 처리
- 로그인 아닌 경우 좋아요/북마크 클릭 시 alert

[FIX] 공지사항 API 동일하게 수정

---

src/components/common/LoginBox/LoginBox.tsx

작성자: @hynseok 
- 현재 stop.scg.skku.ac.kr에서 로그인시 리다이렉트 uri가 localhost* 로 되어있어서 로그인이 안되고 있습니다.  
- 카카오 클라이언트 id 및 리다이렉트 uri 환경변수로 빼서 사용하도록 수정했습니다.
.

[FIX] Update LoginBox.tsx

---

src/components/common/Noticeboard/elements/NoticeItem.tsx
src/types/PageBoardTypes.ts

- `/inquires`, `/proposals` 각각 key 적용, 정상 작동 기대

[FIX] NoticeBoard 컴포넌트 수정

---

src/app/(user)/infodesk/inquiries/page.tsx
src/app/(user)/page.tsx

이슈: #133 
- 관심 프로젝트 등록 취소 오류를 정정했습니다.
- 웍실에서 실시간 확인한 내용이 아니라서 실제로는 해결되지 않았을 수도 있습니다.
- 코드 상 오류를 바로잡은 것이라는 점을 말씀드립니다.

[FIX] 관심 프로젝트 등록 취소 오류 정정

---

src/app/(user)/aihub/models/page.tsx
src/app/(user)/infodesk/inquiries/page.tsx

이슈: #135 
- [v] 적절한 제목으로 수정했나요?
- [v] 상단에 이슈 번호를 기입했나요?
- [v] Target Branch를 올바르게 설정했나요?
- [v] Label을 알맞게 설정했나요?
- 머지 과정에서 짬뽕된 aihub 모델 페이지를 다시 정리하고 inquries를 수정하였습니다
- .

[FIX] aihub model merge code edit, inquires fix

---

src/constants/UserNavigations.ts

- [] 상단에 이슈 번호를 기입했나요?
- constant에 user navigation이 inquiries가 inquries로 되어 있어 제가 만든 소중한 inquiries 페이지가 세상의 빛을 보지 못하고 잇었습니다ㅜ!!
- .

[fix] user navigation inquiries not inquries

---

package.json
src/app/(user)/infodesk/proposals/page.tsx
src/components/pages/AdminProposalsListSection/AdminProposalsListSection.tsx

[HOTFIX] 빌드 오류 해결

---

src/components/common/ProjectCard/ProjectCard.tsx

작성자: @hynseok 
- 제목 클릭은 수정해 주셨는데, 썸네일 클릭이 수정이 안되어있어서 수정했습니다

[FIX] 프로젝트 카드 라우팅 경로 수정

---

.github/workflows/CI.yml

- [] 상단에 이슈 번호를 기입했나요?
- client id에 next_public prefix가 없어 로그인이 안 되는 문제 해결 시도
-

[fix] CI env kakao client id NEXT_PUBLIC prefix

---

src/components/common/LoginBox/LoginBox.tsx

- login box client id prefix edit
- .env.local 파일에 NEXT_PUBLIC_API_ENDPOINT=http://localhost:8000
NEXT_PUBLIC_KAKAO_CLIENT_ID=기존 아이디 찾아서.. 
넣어주셔야 합니다

[fix] login client id prefix edit

---

src/components/common/LoginBox/LoginBox.tsx

[fix] login issue loginbox edit.... again (sorry..)

---

src/app/(user)/interviews/interviews.module.css
src/app/(user)/interviews/page.tsx
src/components/common/VideoCard/DetailModal.tsx
src/components/common/VideoCard/QuizModal.tsx
src/components/common/VideoCard/VideoCard.tsx

이슈: #135 
- 인터뷰 레이아웃 변경 (min size 350으로 키움)
- 로그인 되지 않았을 때 북마크, 퀴즈 풀기 실행 안되게 팝업 띄움
- 퀴즈 호출과 제출 관련 error 상황 시 팝업 띄움
- 비디오카드를 눌렀을 때 상세보기 모달이 뜨도록 코드 수정
- 노퀴즈도 수정 해야 함 ..

[fix] interview layout + videocard modal fix

---

src/components/common/NoticeDetail/NoticeDetail.module.css
src/components/common/NoticeDetail/NoticeDetail.tsx
src/components/common/NoticeDetail/elements/NoticeDetailStage.tsx

작성자: @shj1081 
- `NoticeDetail.Module.css`를 수정하여 줄바꿈 문제 해결
- `NoticeDetailStage.tsx` 에서 미작동 요소들을 제거
.

[FIX] 공지사항, 이벤트공지사항 세부조회 시 줄바꿈 되지 않는 문제해결 와 미작동 버튼 요소들 제거

---

src/app/(user)/event/award/page.tsx
src/app/(user)/event/gallery/page.tsx
src/app/(user)/event/notices/[id]/page.tsx
src/app/(user)/infodesk/proposals/write/page.tsx
src/app/(user)/infodesk/s-top/page.tsx
src/app/(user)/infodesk/s-top/stopExp.module.css
src/app/(user)/jobfair/advices/page.tsx
src/app/(user)/jobfair/interns/page.tsx
src/app/(user)/page.tsx
src/components/common/VideoCard_noQuiz/VideoCard.tsx
src/components/pages/EventAwardView/EventAwardView.module.css
src/components/pages/EventAwardView/EventAwardView.tsx
src/components/pages/MyPage/Mypage.module.css
src/components/pages/MyPage/MypageInterest.tsx

그리드 수정 및 수상결과 페이지 수정

---

src/app/(user)/page.tsx
src/components/common/Noticeboard/elements/NoticeItem.tsx

작성자: @2tle
close #170 
- 갤러리 시간 표시할 데이터를 updatedAt -> createdAt 으로 변경함
- 노티스아이템에서 시간 표시할 데이터를 createdAt > createdData > updatedAt 순으로 변경함.
- 꼼꼼한 코드리뷰 부탁드립니다..!

[FIX] (이벤트)공지사항 및 갤러리 시간 표기 수정

---

src/app/(admin)/admin/page.tsx
src/components/pages/AdminNoticeEditForm/AdminNoticeEditForm.tsx

작성자: @obinox 
- 공지사항 작성칸 사이즈를 늘렸습니다.
- 관리자페이지를 다음과 같이 변경하였습니다.

관리자페이지 메인화면 수정

---

src/components/pages/AdminProjectsEditSection/ProjectsExcelCreateSection.tsx

[FIX] 프로젝트 일괄등록 썸네일, 포스터 여러개 선택 안되는 문제 해결

---

src/app/(user)/jobfair/recruitments/page.tsx
src/components/common/RegisterForm/registerForm.tsx

작성자: @shj1081 
- localhost로 박혀있던 url들 변경

fix: change localhost to serverside

---

src/app/(user)/interviews/interviews.module.css
src/app/(user)/jobfair/advices/jobfair.module.css
src/app/(user)/jobfair/interns/jonfairInterns.module.css
src/app/(user)/jobfair/recruitments/jobfairRe.module.css
src/components/common/CommentBox/CommentBox.tsx
src/components/common/Header/Header.module.css
src/components/common/Noticeboard/Noticeboard.module.css
src/components/common/SubHeadNavbar/SubHeadNavbar.module.css
src/components/pages/ProjectDetail/ProjectDetailComment.tsx
src/components/pages/ProjectDetail/ProjectDetailInfo.tsx
src/styles/UserBoard.module.css

과제 상세페이지 댓글, 잡페어 모바일 화면 수정

---

src/app/(user)/infodesk/cooperation/coop.module.css
src/app/(user)/infodesk/s-top/stopExp.module.css
src/app/(user)/page.tsx
src/components/common/Banner/Banner.module.css
src/components/common/Footer/Footer.module.css
src/components/common/Header/Header.module.css
src/components/common/Header/elements/HandoutShortcut.tsx
src/constants/BannerList.ts

footer, 킹고버스, 배너 설명글 수정

---

src/components/common/Auth/AuthProvider.tsx
src/components/common/Header/Header.module.css
src/components/common/Header/elements/HeaderToolBar.tsx

- [] 상단에 이슈 번호를 기입했나요?
- 모바일 버전에서 헤더에 회원정보가 보이게 수정했습니다
- 새로고침 하지 않으면 회원정보가 안보이는 문제 수정했습니다
- .

[fix] header login 새로고침 수정, 모바일에서 보이게 변경

---

src/app/(admin)/admin/projects/proposals/[id]/page.tsx
src/components/pages/AdminInquiriesEditForm/AdminInquiriesEditForm.tsx
src/components/pages/AdminProposalsListSection/AdminProposalsListSection.tsx

작성자: @obinox 
- 없앴읍니다 너무 오류도 많이 나고 해서...

[FIX] 과제제안 버튼 삭제

---

src/components/common/Header/Header.tsx

작성자: @shj1081 
- 현석님 코드 기반에서 users/me 백엔드 api를 이용하는 방식으로 수정해봤습니다.

[FIX] 유저가드 v2

---

src/components/common/Header/Header.tsx

작성자: @shj1081 
- 빌드 과정에서 reponse가 never used 에러 떠서 사용하지 않느 부분에서 삭제

[FIX} 빌드 에러 수정

---

src/app/(user)/infodesk/proposals/page.tsx
src/app/(user)/infodesk/proposals/pp.module.css
src/app/(user)/jobfair/recruitments/jobfairRe.module.css
src/app/(user)/jobfair/recruitments/page.tsx
src/components/common/Auth/AuthProvider.tsx
src/components/common/Noticeboard/Noticeboard.module.css

과제제안 권한 설정

---

src/components/common/Header/elements/HeaderToolBar.tsx
src/components/pages/MyPage/MypageInterest.tsx

fix: 두 번 하기
작성자: @obinox 
- 패치 내에서 정보를 한번 더 가지고 옵니다.

[FIX ]마이페이지 두 번 하기

---

src/constants/UserNavigations.ts

AI Hub, 채용정보페이지 주석처리

---

src/components/common/Header/Header.tsx
src/components/common/Header/elements/HeaderSymbol.tsx
src/components/common/Header/elements/HeaderToolBar.tsx
src/components/common/Header/elements/HeaderTopNav.tsx

navbar 켜둔 상태에서 다른 곳 넘어가면 꺼지게 함

---

src/components/common/Header/elements/HeaderToolBar.tsx
src/components/pages/MyPage/MypageInterest.tsx

fix: token error

---

src/components/common/Header/elements/HeaderToolBar.tsx

fix: 로그인 후 이름이 안뜨는 문제 해결

---

src/components/common/RegisterForm/registerForm.tsx
src/utils/fetcher/fetcher.ts

[FIX] 첫 로그인 시 이름 정보 로딩 안되는 문제 해결

---

src/utils/fetcher/fetcher.ts

해당 PR의 병합이 원인인지 테스트해보기 위해 revert 해보겠습니다 (prod에서)

Revert "[FIX] 첫 로그인 시 이름 정보 로딩 안되는 문제 해결"

---

src/app/(user)/interviews/page.tsx

- /interview 페이지에서 아래 버튼 미작동 이슈 해결

fix: /interview 페이지에서 대담 영상 북마크 작동 하지 않는 문제 해결

---

src/app/(user)/jobfair/advices/page.tsx
src/app/(user)/jobfair/interns/page.tsx
src/utils/jobInterview/handleJobInterviewBookmarkToggle.ts

- 잡페어 인터뷰 (인턴들의 이야기, 선배님들의 조언)

fix: 잡페어 인터뷰에서 북마크 미작동하는 문제 수정

---

src/components/pages/MyPage/MypageInterest.tsx

fix: 마이페이지에서 북마크 버튼이 올바르게 작동하지 않는 문제를 해결합니다

---

src/app/(user)/interviews/page.tsx
src/app/(user)/jobfair/advices/page.tsx
src/app/(user)/jobfair/interns/page.tsx

fix: /interviews 의 대담 영상 및 잡 인터뷰 영상 첫 로드및 새로고침 시에 북마크 제대로 못 불러오는 현상 수정

---

src/app/(user)/infodesk/s-top/page.tsx

작성자: @2tle
- s-top 인삿말 마지막에 학장님 성함 추가했습니다.

[HOTFIX] 학장님 성함 추가

---

src/app/(user)/infodesk/s-top/page.tsx
src/utils/fetcher/fetcher.ts

[HOTFIX] 학장님 성함 추가 prod 배포용

---

src/app/(user)/projects/(utils)/ProjectSelectTab.tsx
src/components/common/VideoCard/VideoCard.tsx

[HOTFIX] 프로젝트 탭 이름 이벤트 -> 2025, 퀴즈 결과 alert 메시지 수정

---

src/app/(user)/infodesk/s-top/page.tsx
src/app/(user)/projects/(utils)/ProjectSelectTab.tsx
src/components/common/VideoCard/VideoCard.tsx

[HOTFIX] 이벤트 프로젝트->2025프로젝, 퀴즈 결과 alert 메시지 수정

---

src/components/common/Header/Header.module.css
src/components/common/Header/Header.tsx
src/components/common/SubHeadNavbar/SubHeadNavbar.module.css

작성자: @hynseok 
- 핸드아웃 오버레이 클릭시 창 닫힘 기능 추가
- 다크모드 sub navbar 색상 수정
.

[FIX] 핸드아웃 오버레이 클릭시 창 닫힘 기능 추가

---

src/components/common/ProjectCard/ProjectCardLikeSection.tsx
src/components/pages/ProjectDetail/ProjectDetailInfo.tsx

- 프로젝트 목록 페이지 -> 상세보기 페이지로 이동시에는 잘 표시되나,   
상세보기 페이지에서 새로고침 혹은 url을 직접 입력하여 이동하는 경우에는 내 좋아요/북마크 표시가 되지 않는 버그 수정
-

[FIX] 프로젝트 상세보기 페이지 좋아요, 북마크 표시 오류 수정

---

src/constants/LookupTables.ts
src/constants/LookupTables/USER_TYPE_LOOKUP_TABLE.ts
src/types/user.ts

작성자: @shj1081 
- lookuptable 2곳과 role에 external 추가하였습니다.
- 혹시 추가로 수정해야하는데 빠뜨린 부분이 있다면 말씀해주세요..

[FIX] 내 정보 페이지와 수정에서 외부인 핸들링

---

src/components/common/Header/Header.tsx

[FIX] user id 없는 4000번 에러 코드에 대해서도 로그아웃 대응 시도

---

src/components/common/Header/Header.tsx
src/utils/CommonAxios/CommonAxios.ts

[FIX] commonAxios.ts 로 로그인 에러코드 체킹 이동

---

src/utils/CommonAxios/CommonAxios.ts

작성자: @2tle
- axios 인터셉터 내 오류처리 if문들의 순서를 수정했습니다.

[FIX] Interceptor에 있는 오류 if문 순서 수정

---

src/utils/CommonAxios/CommonAxios.ts

[FIX] redirect를 위한 import linen 누락 수정

---

src/app/(user)/layout.module.css
src/components/common/Header/Header.module.css
src/components/common/ProjectCard/ProjectCardLikeSection.tsx
src/theme/fonts/pretendardvariable-dynamic-subset.css

작성자: @hynseok
- 헤더 상단 고정 및 뒷화면 블러처리
- 핸드아웃 오픈시 헤더 아래에 고정

[FIX] 헤더 상단 고정

---

src/app/(user)/layout.module.css
src/components/common/Header/Header.module.css
src/theme/fonts/pretendardvariable-dynamic-subset.css

* fix header css styles
* [FIX] css webkit (trivial)
---------
작성자: @hynseok @chunzhi23

[FIX] 헤더 상단 고정 (#230)

---

src/app/(user)/event/award/page.module.css
src/app/(user)/event/award/page.tsx
src/app/(user)/event/gallery/page.module.css
src/app/(user)/event/gallery/page.tsx
src/app/(user)/interviews/interviews.module.css
src/app/(user)/jobfair/advices/jobfair.module.css
src/app/(user)/jobfair/interns/jonfairInterns.module.css
src/app/(user)/page.tsx
src/components/common/Banner/Banner.module.css
src/components/common/Banner/Banner.tsx
src/components/common/Footer/Footer.module.css
src/components/common/Footer/Footer.tsx
src/components/common/Header/Header.module.css
src/components/common/Header/Header.tsx
src/components/common/SubHeadNavbar/SubHeadNavbar.module.css
src/components/common/SubHeadNavbar/SubHeadNavbar.tsx
src/components/pages/EventGallery/GalleryListSection.module.css
src/components/pages/EventGallery/GalleryListSection.tsx
src/styles/UserBoard.module.css

작성자: @yeobi01 
- 대부분의 페이지에 대해 CSS Layout 수정 작업 진행
- 전체적인 layout 하나에 width를 결정하고 컴포넌트들이 그 width에 맞춰서 css 적용된게 아니라, 제각각 width를 가지고 있어서 장문의 width 미디어쿼리 css를 복붙해서 작업을 했습니다.. 그래서 css 파일이 많이 더러워졌는데, 그래도 기존보다 보기엔 깔끔한 것 같아요
close/resolve/fix #232

[FIX] 전반적인 Layout CSS 통일 작업

---

src/app/(user)/infodesk/cooperation/page.tsx

작성자: @shj1081 
- 기존 이미지 제거 및 누락 섹션 추가

[FIX] changes of cooperation section
